# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
openapi: '3.0.1'
info:
  title: 'backend'
  version: 0.0.1
servers:
  - url: http://localhost:8080/api
    description: Development server
  - url: https://localhost:8080/api
    description: Development server with TLS Profile
tags:
  - name: auth
    description: Authentication / authorization methods
  - name: user
    description: User-specific methods
  - name: 'friends'
    description: Friends and Blocked users
  - name: chat
    description: Messaging

paths:
  '/auth/send_verification_code':
    post:
      description: Send SMS with verification code
      operationId: Auth.SendVerificationCode
      tags:
        - auth
      security: []
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/VerificationCodeRequest'
      responses:
        default:
          description: OK
          content: {} # no body
  '/auth/verify_phone_code':
    post:
      description: Verify the code sent via SMS
      operationId: Auth.VerifyPhoneCode
      tags:
        - auth
      security: []
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/VerifyPhoneCodeRequest'
      responses:
        default:
          description: OK
        '400':
          description: Verification failed
  '/auth/sign_up':
    post:
      description: Adds a new user to the system if they don’t exist yet
      operationId: Auth.SignUp
      tags:
        - auth
      security: []
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        default:
          $ref: '#/components/responses/SignUpResponse'

  '/users':
    get:
      description: Get a list of user IDs
      operationId: Users.Get
      tags:
        - auth
      responses:
        default:
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UsersListResponse'
  '/user/{id}':
    parameters:
      - $ref: '#/components/parameters/UserId'
    get:
      description: Get user info
      operationId: User.GetById
      tags:
        - user
      responses:
        default:
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/UserInfoResponse'
  '/user/{id}/logout':
    parameters:
      - $ref: '#/components/parameters/UserId'
    post:
      description: Logs a user out of the system
      operationId: User.Logout
      tags:
        - user
      responses:
        default:
          $ref: '#/components/responses/BasicResponse'

  '/user/{id}/get_partner':
    parameters:
      - $ref: '#/components/parameters/UserId'
    get:
      description: Tries to get a partner for a given user
      operationId: User.Id.Partner.Get
      tags:
        - user
      responses:
        default:
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PartnerResponse'

  '/user/{id}/friends':
    parameters:
      - $ref: '#/components/parameters/UserId'
    get:
      description: Retrieve a list of user’s friends
      operationId: User.Id.Friends.Get
      tags:
        - friends
      responses:
        default:
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/FriendsListResponse'
  '/user/{id}/add_friend':
    parameters:
      - $ref: '#/components/parameters/UserId'
    post:
      description: Adds a friend to a list of user’s friends, if possible
      operationId: User.Id.Friends.Add.Post
      tags:
        - friends
      requestBody:
        $ref: '#/components/requestBodies/FriendIdRequestBody'
      responses:
        default:
          $ref: '#/components/responses/BasicResponse'
  '/user/{id}/remove_friend':
    parameters:
      - $ref: '#/components/parameters/UserId'
    post:
      description: Removes a friend for a list of user’s friends, if possible
      operationId: User.Id.Friends.Remove.Post
      tags:
        - friends
      requestBody:
        $ref: '#/components/requestBodies/FriendIdRequestBody'
      responses:
        default:
          $ref: '#/components/responses/BasicResponse'
  '/user/{id}/report':
    parameters:
      - $ref: '#/components/parameters/UserId'
    post:
      description: Reports another user as having “bad behaviour” and adds them to the list of users blocked by the given user.
      operationId: User.Id.Report.Post
      tags:
        - friends
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/ReportRequest'
      responses:
        default:
          $ref: '#/components/responses/BasicResponse'
  '/user/{id}/blocked':
    parameters:
      - $ref: '#/components/parameters/UserId'
    get:
      description: Returns the list of users blocked for the given user
      operationId: User.Id.Blocked.Get
      tags:
        - friends
      responses:
        default:
          $ref: '#/components/schemas/BlockedUsersResponse'

  '/user/{id}/send_message':
    parameters:
      - $ref: '#/components/parameters/UserId'
    post:
      description: Sends a message to another user.
      operationId: User.Id.SendMessage.Post
      tags:
        - chat
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        default:
          $ref: '#/components/responses/SentMessage'
  '/user/{id}/messages/{peer_id}':
    parameters:
      - $ref: '#/components/parameters/UserId'
      - name: peer_id
        in: path
        description: Receiver user ID
        required: true
        schema:
          $ref: '#/components/schemas/UserId'
    post:
      description: Retrieve all chat history with peer.
      operationId: User.Id.Messages.Post
      tags:
        - chat
      responses:
        default:
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/MessagesResponse'
components:
  requestBodies:
    FriendIdRequestBody:
      description: Specifies user ID of a friend
      required: true
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/FriendIdObject'
  parameters:
    UserId:
      name: id
      in: path
      required: true
      description: ID of a user
      schema:
        $ref: '#/components/schemas/UserId'
  schemas:
    UserId:
      type: integer
    Phone:
      type: string
      description: Phone number. Stripped from any punctuation except for leading '+'.
      pattern: '\+[0-9]{7,20}'
    VerificationCode:
      type: string
      description: Verification code from SMS. 4-digits string.
      pattern: '[0-9]{4}'
    AgeGroup:
      type: string
      enum:
        - '<18'
        - '18-25'
        - '26-35'
        - '36-45'
        - '>45'
    LanguageSpec:
      type: string
      description: https://docs.oracle.com/javase/tutorial/i18n/locale/matching.html
      enum:
        - 'en-US'
        - 'ru-RU'
        - 'fr-FR'
        - 'it-IT'
        - 'es-ES'
    ResponseBase:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
        error_message:
          type: string

    UserIdList:
      type: array
      items:
        $ref: '#/components/schemas/UserId'
    UserInfo:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UserId'
        name:
          type: string
        age_group:
          $ref: '#/components/schemas/AgeGroup'
        language:
          $ref: '#/components/schemas/LanguageSpec'
      required:
        - id
        - name
        - age_group
        - language
    UserInfoSelf:
      type: object
      properties:
        public:
          $ref: '#/components/schemas/UserInfo'
        private:
          type: object
          properties:
            phone:
              $ref: '#/components/schemas/Phone'
            token:
              description: Authentication token
              type: string
          required:
            - prone
            - token
      required:
        - public
        - private

    VerificationCodeRequest:
      type: object
      properties:
        phone:
          $ref: '#/components/schemas/Phone'
      required:
        - phone
    VerifyPhoneCodeRequest:
      type: object
      properties:
        phone:
          $ref: '#/components/schemas/Phone'
        code:
          $ref: '#/components/schemas/VerificationCode'
      required:
        - phone
        - code

    SignUpRequest:
      type: object
      properties:
        phone:
          $ref: '#/components/schemas/Phone'
        code:
          $ref: '#/components/schemas/VerificationCode'
        name:
          type: string
        age_group:
          $ref: '#/components/schemas/AgeGroup'
        language:
          $ref: '#/components/schemas/LanguageSpec'
      required:
        - phone
        - code
        - name
        - age_group
        - language
    SignUpResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
        error_message:
          type: string
        me:
          $ref: '#/components/schemas/UserInfoSelf'

    UsersListResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
        error_message:
          type: string
        user_ids:
          $ref: '#/components/schemas/UserIdList'
    UserInfoResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
        error_message:
          type: string
        user:
          $ref: '#/components/schemas/UserInfo'

    PartnerResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
        error_message:
          type: string
        partner_id:
          $ref: '#/components/schemas/UserId'

    FriendId:
      type: object
      required:
        - friend_id
      properties:
        friend_id:
          $ref: '#/components/schemas/UserId'
    FriendsListResponse:
      type: object
      required:
        - status
        - friend_ids
      properties:
        status:
          type: integer
        error_message:
          type: string
        friend_ids:
          type: array
          items:
            $ref: '#/components/schemas/UserId'
    FriendIdObject:
      type: object
      required:
        - friend_id
      properties:
        friend_id:
          $ref: '#/components/schemas/UserId'
    ReportRequest:
      type: object
      required:
        - report_reason
        - reported_id
      properties:
        report_reason:
          type: integer
        reported_id:
          type: integer
    BlockedUsersResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
        error_message:
          type: string
        blocked:
          type: array
          items:
            $ref: '#/components/schemas/UserId'

    MessageId:
      description: Globally unique message ID
      type: integer
    MessageRequest:
      type: object
      description: |
        Message ID of `reply_to_message_id` must belong to the same chat.
        At least `message` or `image` must be non-empty.
        `image` is base64 encoded jpeg file.
      required:
        - receiver_id
      properties:
        receiver_id:
          $ref: '#/components/schemas/UserId'
        message:
          type: string
        image:
          type: string
          format: byte
        reply_to_message_id:
          $ref: '#/components/schemas/MessageId'
    SentMessage:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
        error_message:
          type: string
        message_id:
          $ref: '#/components/schemas/MessageId'
    MessagesResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: integer
        error_message:
          type: string
        messages:
          $ref: '#/components/schemas/Messages'
    Messages:
      type: array
      items:
        $ref: '#/components/schemas/Message'
    Message:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/MessageId'
        incoming:
          type: boolean
          description: Shortcut for comparing sender with current user's ID.
        sender:
          $ref: '#/components/schemas/UserId'
        receiver:
          $ref: '#/components/schemas/UserId'
        message:
          type: string
        image:
          type: string
          format: byte
        reply_to_message_id:
          $ref: '#/components/schemas/MessageId'
  responses:
    BasicResponse:
      description: Basic response
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/ResponseBase'

    SignUpResponse:
      description: User registered and automatically logged in
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/SignUpResponse'

    SentMessage:
      description: Wrapper for `SentMessage` scheme.
      content:
        'application/json':
          schema:
            $ref: '#/components/schemas/SentMessage'
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT # optional, arbitrary value for documentation purposes#    jwt:
security:
  - bearerAuth: []
