# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_id import UserId  # noqa: F401,E501
from swagger_server import util


class BlockedUsersResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, error_message: str=None, blocked: List[UserId]=None):  # noqa: E501
        """BlockedUsersResponse - a model defined in Swagger

        :param status: The status of this BlockedUsersResponse.  # noqa: E501
        :type status: int
        :param error_message: The error_message of this BlockedUsersResponse.  # noqa: E501
        :type error_message: str
        :param blocked: The blocked of this BlockedUsersResponse.  # noqa: E501
        :type blocked: List[UserId]
        """
        self.swagger_types = {
            'status': int,
            'error_message': str,
            'blocked': List[UserId]
        }

        self.attribute_map = {
            'status': 'status',
            'error_message': 'error_message',
            'blocked': 'blocked'
        }
        self._status = status
        self._error_message = error_message
        self._blocked = blocked

    @classmethod
    def from_dict(cls, dikt) -> 'BlockedUsersResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BlockedUsersResponse of this BlockedUsersResponse.  # noqa: E501
        :rtype: BlockedUsersResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this BlockedUsersResponse.


        :return: The status of this BlockedUsersResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this BlockedUsersResponse.


        :param status: The status of this BlockedUsersResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error_message(self) -> str:
        """Gets the error_message of this BlockedUsersResponse.


        :return: The error_message of this BlockedUsersResponse.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this BlockedUsersResponse.


        :param error_message: The error_message of this BlockedUsersResponse.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def blocked(self) -> List[UserId]:
        """Gets the blocked of this BlockedUsersResponse.


        :return: The blocked of this BlockedUsersResponse.
        :rtype: List[UserId]
        """
        return self._blocked

    @blocked.setter
    def blocked(self, blocked: List[UserId]):
        """Sets the blocked of this BlockedUsersResponse.


        :param blocked: The blocked of this BlockedUsersResponse.
        :type blocked: List[UserId]
        """

        self._blocked = blocked
