# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.image import Image  # noqa: F401,E501
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, image: Image=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param image: The image of this Body.  # noqa: E501
        :type image: Image
        """
        self.swagger_types = {
            'image': Image
        }

        self.attribute_map = {
            'image': 'image'
        }
        self._image = image

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image(self) -> Image:
        """Gets the image of this Body.


        :return: The image of this Body.
        :rtype: Image
        """
        return self._image

    @image.setter
    def image(self, image: Image):
        """Sets the image of this Body.


        :param image: The image of this Body.
        :type image: Image
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image
