# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bookmark_object import BookmarkObject  # noqa: F401,E501
from swagger_server import util


class BookmarksListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, error_message: str=None, bookmarks: List[BookmarkObject]=None):  # noqa: E501
        """BookmarksListResponse - a model defined in Swagger

        :param status: The status of this BookmarksListResponse.  # noqa: E501
        :type status: int
        :param error_message: The error_message of this BookmarksListResponse.  # noqa: E501
        :type error_message: str
        :param bookmarks: The bookmarks of this BookmarksListResponse.  # noqa: E501
        :type bookmarks: List[BookmarkObject]
        """
        self.swagger_types = {
            'status': int,
            'error_message': str,
            'bookmarks': List[BookmarkObject]
        }

        self.attribute_map = {
            'status': 'status',
            'error_message': 'error_message',
            'bookmarks': 'bookmarks'
        }
        self._status = status
        self._error_message = error_message
        self._bookmarks = bookmarks

    @classmethod
    def from_dict(cls, dikt) -> 'BookmarksListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookmarksListResponse of this BookmarksListResponse.  # noqa: E501
        :rtype: BookmarksListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this BookmarksListResponse.


        :return: The status of this BookmarksListResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this BookmarksListResponse.


        :param status: The status of this BookmarksListResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error_message(self) -> str:
        """Gets the error_message of this BookmarksListResponse.


        :return: The error_message of this BookmarksListResponse.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this BookmarksListResponse.


        :param error_message: The error_message of this BookmarksListResponse.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def bookmarks(self) -> List[BookmarkObject]:
        """Gets the bookmarks of this BookmarksListResponse.


        :return: The bookmarks of this BookmarksListResponse.
        :rtype: List[BookmarkObject]
        """
        return self._bookmarks

    @bookmarks.setter
    def bookmarks(self, bookmarks: List[BookmarkObject]):
        """Sets the bookmarks of this BookmarksListResponse.


        :param bookmarks: The bookmarks of this BookmarksListResponse.
        :type bookmarks: List[BookmarkObject]
        """
        if bookmarks is None:
            raise ValueError("Invalid value for `bookmarks`, must not be `None`")  # noqa: E501

        self._bookmarks = bookmarks
