# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.messages import Messages  # noqa: F401,E501
from swagger_server import util


class MessagesResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, error_message: str=None, messages: Messages=None):  # noqa: E501
        """MessagesResponse - a model defined in Swagger

        :param status: The status of this MessagesResponse.  # noqa: E501
        :type status: int
        :param error_message: The error_message of this MessagesResponse.  # noqa: E501
        :type error_message: str
        :param messages: The messages of this MessagesResponse.  # noqa: E501
        :type messages: Messages
        """
        self.swagger_types = {
            'status': int,
            'error_message': str,
            'messages': Messages
        }

        self.attribute_map = {
            'status': 'status',
            'error_message': 'error_message',
            'messages': 'messages'
        }
        self._status = status
        self._error_message = error_message
        self._messages = messages

    @classmethod
    def from_dict(cls, dikt) -> 'MessagesResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MessagesResponse of this MessagesResponse.  # noqa: E501
        :rtype: MessagesResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this MessagesResponse.


        :return: The status of this MessagesResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this MessagesResponse.


        :param status: The status of this MessagesResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error_message(self) -> str:
        """Gets the error_message of this MessagesResponse.


        :return: The error_message of this MessagesResponse.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this MessagesResponse.


        :param error_message: The error_message of this MessagesResponse.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def messages(self) -> Messages:
        """Gets the messages of this MessagesResponse.


        :return: The messages of this MessagesResponse.
        :rtype: Messages
        """
        return self._messages

    @messages.setter
    def messages(self, messages: Messages):
        """Sets the messages of this MessagesResponse.


        :param messages: The messages of this MessagesResponse.
        :type messages: Messages
        """

        self._messages = messages
