# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_id import UserId  # noqa: F401,E501
from swagger_server import util


class PartnerResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, error_message: str=None, partner_id: UserId=None):  # noqa: E501
        """PartnerResponse - a model defined in Swagger

        :param status: The status of this PartnerResponse.  # noqa: E501
        :type status: int
        :param error_message: The error_message of this PartnerResponse.  # noqa: E501
        :type error_message: str
        :param partner_id: The partner_id of this PartnerResponse.  # noqa: E501
        :type partner_id: UserId
        """
        self.swagger_types = {
            'status': int,
            'error_message': str,
            'partner_id': UserId
        }

        self.attribute_map = {
            'status': 'status',
            'error_message': 'error_message',
            'partner_id': 'partner_id'
        }
        self._status = status
        self._error_message = error_message
        self._partner_id = partner_id

    @classmethod
    def from_dict(cls, dikt) -> 'PartnerResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PartnerResponse of this PartnerResponse.  # noqa: E501
        :rtype: PartnerResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this PartnerResponse.


        :return: The status of this PartnerResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this PartnerResponse.


        :param status: The status of this PartnerResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error_message(self) -> str:
        """Gets the error_message of this PartnerResponse.


        :return: The error_message of this PartnerResponse.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this PartnerResponse.


        :param error_message: The error_message of this PartnerResponse.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def partner_id(self) -> UserId:
        """Gets the partner_id of this PartnerResponse.


        :return: The partner_id of this PartnerResponse.
        :rtype: UserId
        """
        return self._partner_id

    @partner_id.setter
    def partner_id(self, partner_id: UserId):
        """Sets the partner_id of this PartnerResponse.


        :param partner_id: The partner_id of this PartnerResponse.
        :type partner_id: UserId
        """

        self._partner_id = partner_id
