# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.message_id import MessageId  # noqa: F401,E501
from swagger_server import util


class SentMessage(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, error_message: str=None, message_id: MessageId=None):  # noqa: E501
        """SentMessage - a model defined in Swagger

        :param status: The status of this SentMessage.  # noqa: E501
        :type status: int
        :param error_message: The error_message of this SentMessage.  # noqa: E501
        :type error_message: str
        :param message_id: The message_id of this SentMessage.  # noqa: E501
        :type message_id: MessageId
        """
        self.swagger_types = {
            'status': int,
            'error_message': str,
            'message_id': MessageId
        }

        self.attribute_map = {
            'status': 'status',
            'error_message': 'error_message',
            'message_id': 'message_id'
        }
        self._status = status
        self._error_message = error_message
        self._message_id = message_id

    @classmethod
    def from_dict(cls, dikt) -> 'SentMessage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SentMessage of this SentMessage.  # noqa: E501
        :rtype: SentMessage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this SentMessage.


        :return: The status of this SentMessage.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this SentMessage.


        :param status: The status of this SentMessage.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error_message(self) -> str:
        """Gets the error_message of this SentMessage.


        :return: The error_message of this SentMessage.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this SentMessage.


        :param error_message: The error_message of this SentMessage.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def message_id(self) -> MessageId:
        """Gets the message_id of this SentMessage.


        :return: The message_id of this SentMessage.
        :rtype: MessageId
        """
        return self._message_id

    @message_id.setter
    def message_id(self, message_id: MessageId):
        """Sets the message_id of this SentMessage.


        :param message_id: The message_id of this SentMessage.
        :type message_id: MessageId
        """

        self._message_id = message_id
