# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_id_list import UserIdList  # noqa: F401,E501
from swagger_server import util


class UsersListResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, error_message: str=None, user_ids: UserIdList=None):  # noqa: E501
        """UsersListResponse - a model defined in Swagger

        :param status: The status of this UsersListResponse.  # noqa: E501
        :type status: int
        :param error_message: The error_message of this UsersListResponse.  # noqa: E501
        :type error_message: str
        :param user_ids: The user_ids of this UsersListResponse.  # noqa: E501
        :type user_ids: UserIdList
        """
        self.swagger_types = {
            'status': int,
            'error_message': str,
            'user_ids': UserIdList
        }

        self.attribute_map = {
            'status': 'status',
            'error_message': 'error_message',
            'user_ids': 'user_ids'
        }
        self._status = status
        self._error_message = error_message
        self._user_ids = user_ids

    @classmethod
    def from_dict(cls, dikt) -> 'UsersListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UsersListResponse of this UsersListResponse.  # noqa: E501
        :rtype: UsersListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this UsersListResponse.


        :return: The status of this UsersListResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this UsersListResponse.


        :param status: The status of this UsersListResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error_message(self) -> str:
        """Gets the error_message of this UsersListResponse.


        :return: The error_message of this UsersListResponse.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this UsersListResponse.


        :param error_message: The error_message of this UsersListResponse.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def user_ids(self) -> UserIdList:
        """Gets the user_ids of this UsersListResponse.


        :return: The user_ids of this UsersListResponse.
        :rtype: UserIdList
        """
        return self._user_ids

    @user_ids.setter
    def user_ids(self, user_ids: UserIdList):
        """Sets the user_ids of this UsersListResponse.


        :param user_ids: The user_ids of this UsersListResponse.
        :type user_ids: UserIdList
        """

        self._user_ids = user_ids
