# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.age_group import AgeGroup  # noqa: F401,E501
from swagger_server.models.image import Image  # noqa: F401,E501
from swagger_server.models.language_spec import LanguageSpec  # noqa: F401,E501
from swagger_server.models.user_id import UserId  # noqa: F401,E501
from swagger_server import util


class UserInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: UserId=None, name: str=None, age_group: AgeGroup=None, language: LanguageSpec=None, image: Image=None):  # noqa: E501
        """UserInfo - a model defined in Swagger

        :param id: The id of this UserInfo.  # noqa: E501
        :type id: UserId
        :param name: The name of this UserInfo.  # noqa: E501
        :type name: str
        :param age_group: The age_group of this UserInfo.  # noqa: E501
        :type age_group: AgeGroup
        :param language: The language of this UserInfo.  # noqa: E501
        :type language: LanguageSpec
        :param image: The image of this UserInfo.  # noqa: E501
        :type image: Image
        """
        self.swagger_types = {
            'id': UserId,
            'name': str,
            'age_group': AgeGroup,
            'language': LanguageSpec,
            'image': Image
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'age_group': 'age_group',
            'language': 'language',
            'image': 'image'
        }
        self._id = id
        self._name = name
        self._age_group = age_group
        self._language = language
        self._image = image

    @classmethod
    def from_dict(cls, dikt) -> 'UserInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInfo of this UserInfo.  # noqa: E501
        :rtype: UserInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> UserId:
        """Gets the id of this UserInfo.


        :return: The id of this UserInfo.
        :rtype: UserId
        """
        return self._id

    @id.setter
    def id(self, id: UserId):
        """Sets the id of this UserInfo.


        :param id: The id of this UserInfo.
        :type id: UserId
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this UserInfo.


        :return: The name of this UserInfo.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this UserInfo.


        :param name: The name of this UserInfo.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def age_group(self) -> AgeGroup:
        """Gets the age_group of this UserInfo.


        :return: The age_group of this UserInfo.
        :rtype: AgeGroup
        """
        return self._age_group

    @age_group.setter
    def age_group(self, age_group: AgeGroup):
        """Sets the age_group of this UserInfo.


        :param age_group: The age_group of this UserInfo.
        :type age_group: AgeGroup
        """
        if age_group is None:
            raise ValueError("Invalid value for `age_group`, must not be `None`")  # noqa: E501

        self._age_group = age_group

    @property
    def language(self) -> LanguageSpec:
        """Gets the language of this UserInfo.


        :return: The language of this UserInfo.
        :rtype: LanguageSpec
        """
        return self._language

    @language.setter
    def language(self, language: LanguageSpec):
        """Sets the language of this UserInfo.


        :param language: The language of this UserInfo.
        :type language: LanguageSpec
        """
        if language is None:
            raise ValueError("Invalid value for `language`, must not be `None`")  # noqa: E501

        self._language = language

    @property
    def image(self) -> Image:
        """Gets the image of this UserInfo.


        :return: The image of this UserInfo.
        :rtype: Image
        """
        return self._image

    @image.setter
    def image(self, image: Image):
        """Sets the image of this UserInfo.


        :param image: The image of this UserInfo.
        :type image: Image
        """
        if image is None:
            raise ValueError("Invalid value for `image`, must not be `None`")  # noqa: E501

        self._image = image
