# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.user_info import UserInfo  # noqa: F401,E501
from swagger_server import util


class UserInfoResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, status: int=None, error_message: str=None, user: UserInfo=None):  # noqa: E501
        """UserInfoResponse - a model defined in Swagger

        :param status: The status of this UserInfoResponse.  # noqa: E501
        :type status: int
        :param error_message: The error_message of this UserInfoResponse.  # noqa: E501
        :type error_message: str
        :param user: The user of this UserInfoResponse.  # noqa: E501
        :type user: UserInfo
        """
        self.swagger_types = {
            'status': int,
            'error_message': str,
            'user': UserInfo
        }

        self.attribute_map = {
            'status': 'status',
            'error_message': 'error_message',
            'user': 'user'
        }
        self._status = status
        self._error_message = error_message
        self._user = user

    @classmethod
    def from_dict(cls, dikt) -> 'UserInfoResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserInfoResponse of this UserInfoResponse.  # noqa: E501
        :rtype: UserInfoResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> int:
        """Gets the status of this UserInfoResponse.


        :return: The status of this UserInfoResponse.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status: int):
        """Sets the status of this UserInfoResponse.


        :param status: The status of this UserInfoResponse.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def error_message(self) -> str:
        """Gets the error_message of this UserInfoResponse.


        :return: The error_message of this UserInfoResponse.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this UserInfoResponse.


        :param error_message: The error_message of this UserInfoResponse.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def user(self) -> UserInfo:
        """Gets the user of this UserInfoResponse.


        :return: The user of this UserInfoResponse.
        :rtype: UserInfo
        """
        return self._user

    @user.setter
    def user(self, user: UserInfo):
        """Sets the user of this UserInfoResponse.


        :param user: The user of this UserInfoResponse.
        :type user: UserInfo
        """

        self._user = user
