# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.phone import Phone  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class VerificationCodeRequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, phone: Phone=None):  # noqa: E501
        """VerificationCodeRequest - a model defined in Swagger

        :param phone: The phone of this VerificationCodeRequest.  # noqa: E501
        :type phone: Phone
        """
        self.swagger_types = {
            'phone': Phone
        }

        self.attribute_map = {
            'phone': 'phone'
        }
        self._phone = phone

    @classmethod
    def from_dict(cls, dikt) -> 'VerificationCodeRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerificationCodeRequest of this VerificationCodeRequest.  # noqa: E501
        :rtype: VerificationCodeRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def phone(self) -> Phone:
        """Gets the phone of this VerificationCodeRequest.


        :return: The phone of this VerificationCodeRequest.
        :rtype: Phone
        """
        return self._phone

    @phone.setter
    def phone(self, phone: Phone):
        """Sets the phone of this VerificationCodeRequest.


        :param phone: The phone of this VerificationCodeRequest.
        :type phone: Phone
        """
        if phone is None:
            raise ValueError("Invalid value for `phone`, must not be `None`")  # noqa: E501

        self._phone = phone
